# Generated by Django 2.2 on 2019-04-26 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='idm',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator, django.core.validators.RegexValidator(message='IDm must be 16-digit hexadecimal number', regex='^[0-9A-F]{16}$')], verbose_name='FeliCa ID'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='idm',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator, django.core.validators.RegexValidator(message='IDm must be 16-digit hexadecimal number', regex='^[0-9A-F]{16}$')], verbose_name='FeliCa ID'),
        ),
    ]
