# Generated by Django 2.2 on 2019-04-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='ゲスト'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100, verbose_name='カード名'),
        ),
    ]
