# Generated by Django 2.2 on 2019-04-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190412_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'ICカード', 'verbose_name_plural': 'ICカード'},
        ),
    ]
