# Generated by Django 2.2.1 on 2019-09-05 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190429_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('8d7612c5-59f9-427e-94c9-f7ce5e2ffbc9'), editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効性')),
                ('generated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成された時間')),
                ('registered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザー')),
            ],
            options={
                'verbose_name': '招待',
                'verbose_name_plural': '招待',
            },
        ),
    ]
