version: '3'
services:
  base:
    build: ./docker/base
    image: djangobase

  django:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
    expose:
      - "3031"
    env_file:
      - ./db.env
    command: bash -c "cd /opt/apps/ && python manage.py migrate --run-syncdb && python manage.py collectstatic --noinput && gunicorn kagipos.wsgi -b 0.0.0.0:3031"
    volumes:
      - "staticdata:/opt/static/"
      - "./:/opt/apps/"
  nginx:
    restart: always
    image: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/:/etc/nginx/"
      - "staticdata:/opt/apps/static/"

volumes:
  staticdata:
