# Generated by Django 2.2 on 2019-04-12 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=True, verbose_name='ゲスト')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='カード名')),
                ('idm', models.BigIntegerField(unique=True, verbose_name='FeliCa ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='所持ユーザー')),
            ],
        ),
    ]
