# Generated by Django 2.2 on 2019-04-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('possys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': '取引履歴', 'verbose_name_plural': '取引履歴'},
        ),
    ]
