# Generated by Django 2.2 on 2019-04-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('possys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': '取引', 'verbose_name_plural': '取引'},
        ),
    ]
